apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: MI Hello world
      port: 8290
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: helloConfigs/src/main/resources/metadata/HelloWorld_swagger.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/publishercomponent1/8b1c3/v1/PUBLIC
      connectionConfig: 01f0095c-4489-1ad6-8e3e-303ef8fb07cb
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
