apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Go Greeter
      port: 9090
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/connections/ktwgzp/8b1c3/v1.0/PUBLIC
      connectionConfig: 01ef022d-d1e4-1eee-9321-3c8e4362bf0a
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
