openapi: 3.0.1
info:
  title: Hello
  version: 3.1.1
servers:
- url: "{server}:{port}/hello"
  variables:
    server:
      default: http://localhost
    port:
      default: "8090"
paths:
  /greeting:
    get:
      operationId: getGreeting
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
